### PR TITLE
Create Api for the backend

### PR DESCRIPTION
**Pull request by mandelatuks**
### In this PR i did the following:

- Create a new Rails API app called 'hello-rails-back-end'.
- Initialize your project with Git.
- Make sure that your project has a Postgres database set up.
- Create a table for storing your messages and create 5 different greetings.
- Create an API endpoint that selects a random greeting from your table (you will need a controller with an action an rails route).
- [the link to the Front-end-repohttps](github.com/mandelatuks/hello-react-front-end/pull/1)
~~~
hi,Reviewer 
for you run this project you will have to run this backed to localhost 3000/api/v1/greeetings

then after run react app thank you 
~~~

### CODE REVIEW

**Review by m05e5 — CHANGES_REQUESTED** [review]
Hi @mandelatuks , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a PR that has merge conflicts with the dev branch. Please kindly fix the merge conflicts and resubmit for review

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by mandelatuks** [comment]
@m05e5
solved the conflict

**Review by medaminedev66 — APPROVED** [review]
Hi @mandelatuks  😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 💯 
Congratulations! 🎉 

### Highlights
- The Back-end and the Front-end apps work together.
- The React app displays a random greeting

### Optional suggestions
- I recommend updating the Readme file of the front-end repo with the proper one so that your project is professional.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mandelatuks** [comment]
@medaminedev66 thank you for the approval happy coding 🕺🏿🤓

**Pull request merged**
